name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: {}

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          cache: true

      - name: Format
        run: deno fmt --check
      - name: Build
        run: deno task build
